name: CI
on:
  push:
    branches: [ main, env/**, feat/** ]
    paths:
      - 'labs/**'
      - '.github/workflows/ci.yml'
      - '.flake8'
  pull_request:
    paths:
      - 'labs/**'
      - '.github/workflows/ci.yml'
      - '.flake8'

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    container:
      image: ghcr.io/bozdogalex/bioinf-y4-lab:base
    steps:
      - uses: actions/checkout@v4
      - name: flake8 (lab 01 only, temporary)
        run: flake8 labs/01_intro\&databases


  smoke:
    name: smoke
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    container:
      image: ghcr.io/bozdogalex/bioinf-y4-lab:base
    steps:
      - uses: actions/checkout@v4
      - name: Lint (only smoke)
        run: flake8 labs/00_smoke
      - name: Run smoke
        run: python labs/00_smoke/smoke.py

  mlflow:
    name: mlflow
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    container:
      image: ghcr.io/bozdogalex/bioinf-y4-lab:base
    steps:
      - uses: actions/checkout@v4
      - name: MLflow smoke (no UI)
        run: python labs/00_smoke/mlflow_smoke.py --experiment "BIOINF-Y4 Demo"
