name: Publish Docker image

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write     # push to GHCR
    steps:
      - uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push (bioinf-y4:base)
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/bozdogalex/bioinf-y4:base
          labels: |
            org.opencontainers.image.source=https://github.com/bozdogalex/bioinf-y4-lab
            org.opencontainers.image.title=BIOINF-Y4 base
            org.opencontainers.image.description=CPU-only base image for BIOINF-Y4 labs
          cache-from: type=gha
          cache-to: type=gha,mode=max
