name: Publish Docker image

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

# Give the GITHUB_TOKEN the scopes we need (top-level, explicit)
permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to GHCR (owner namespace)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push (bioinf-y4:base)
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/bioinf-y4:base
          labels: |
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
            org.opencontainers.image.title=BIOINF-Y4 base
            org.opencontainers.image.description=CPU-only base image for BIOINF-Y4 labs
          cache-from: type=gha
          cache-to: type=gha,mode=max
