name: Validate PR Template
on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  week1:
    name: week1
    runs-on: ubuntu-latest
    steps:
      - name: Check PR body for Week 1 template marker
        if: |
          contains(github.event.pull_request.head.ref, 'feat/roster-') ||
          contains(github.event.pull_request.title, 'Săptămâna 1') ||
          contains(github.event.pull_request.title, 'Week 1')
        run: |
          BODY="$(jq -r '.pull_request.body' < "$GITHUB_EVENT_PATH")"
          echo "$BODY" | grep -q "Săptămâna 1 — Roster PR" || {
            echo "::error::Lipsește șablonul Week 1 (week1_roster.md). Deschideți PR-ul și alegeți *Choose a template* → *week1_roster.md*."
            exit 1
          }

  # Skeleton for future weeks — uncomment & adapt when week templates exist
  # week2:
  #   name: week2
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Check PR body for Week 2 template marker
  #       if: |
  #         contains(github.event.pull_request.head.ref, 'feat/week2-') ||
  #         contains(github.event.pull_request.title, 'Săptămâna 2') ||
  #         contains(github.event.pull_request.title, 'Week 2')
  #       run: |
  #         BODY="$(jq -r '.pull_request.body' < "$GITHUB_EVENT_PATH")"
  #         echo "$BODY" | grep -q "Săptămâna 2 — Alignment PR" || {
  #           echo "::error::Lipsește șablonul Week 2. Alegeți *week2_alignment.md*."
  #           exit 1
  #         }
